config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :logs
  resources :tasks
  resources :projects
  resources :members
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/about'
  get 'home/index'
  root 'home#index'
  get ':ViewCode', to: 'projects#show', as: :ViewCode
  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ActionController::Base
	def index

	end
	def about

	end
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark container-fluid" style="justify-content: space-between;">
      <div class="left" style="display:flex; flex-direction: row;">
        <a class="navbar-brand" href="/">Scheduler</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div style="display:flex; flex-direction: row">
            <!--<%= link_to 'HOME', root_path, class:"nav-link" %>-->
            <a class="nav-link" href="/home/index">HOME</a>
            <a class="nav-link" href="/home/about">ABOUT</a>
            <!-- <%= link_to 'Members', members_path, class:"nav-link" %>-->
            <%= link_to 'Projects', projects_path, class:"nav-link" %>
            <%= link_to 'Tasks', tasks_path, class:"nav-link" %>
            <%= link_to 'Logs', logs_path, class:"nav-link" %>
          </div>
        </div>
      </div>
      <div class="right" style="display:flex; flex-direction: row;">
        <%if user_signed_in?%>
        <%= link_to 'Profile', edit_user_registration_url, class:"nav-link" %>
        <%= link_to current_user.email, "#", {:style=>'display:flex;justify-content:flex-end', :class => 'nav-link'} %>
        <%= link_to 'Logout', destroy_user_session_path, class:"nav-link" %>
        <%else%>
        <%= link_to 'Login', new_user_session_url, class:"nav-link" %>
        <%= link_to 'Register', new_user_registration_path, class:"nav-link" %>
        <%end%>
      </div>
</nav>

app/views/home/about.html.erb
<html>
  <head>
    <title>ProjectQueuer</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
<body>
  <p style="color: green"><%= notice %></p>
      <%= render 'home/header' %>
<div class="container">
  <br/>
	<h1>
		The route is clear!
	</h1>
  <br/>
  <h4>
    Here we're gonna plan this production out.
  </h4>
</div>
</body>
</html>

app/views/home/index.html.erb
<html>
  <head>
    <title>Scheduler</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <style type="text/css">
    .center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}
  </style>
<body>
  <p style="color: green"><%= notice %></p>
  <%= render 'home/header' %>
<div class="container">
    
    <div>
    <div class="container" style="display: flex;align-items: stretch;">
		<img class="center" src="https://cdn.pixabay.com/photo/2017/06/10/06/39/calender-2389150_960_720.png"/>
  </div>
</div>
</div>
</body>
</html>