config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
   get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :logs
  resources :tasks
  resources :projects
  resources :members
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'home/about'
  get 'home/index'
  root 'home#index'
  get ':ViewCode', to: 'projects#show', as: :ViewCode
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/log.rb
class Log < ApplicationRecord
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :set_log, only: %i[ show edit update destroy ]

  # GET /logs or /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1 or /logs/1.json
  def show

  end

  # GET /logs/new
  def new
    @task_types = {1=>"Desktop", 2=>"Mobile", 3=>"Web app", 4=>"Crossplatform", 5=>"Game"}
    @task_priority = {1 => "Low", 2 => "Medium", 3 => "High"}
    @log = Log.new
  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs or /logs.json
  def create
    if project_exists
      @log = Log.new(log_params)
      respond_to do |format|
        if @log.save
          format.html { redirect_to log_url(@log), notice: "Log was successfully created." }
          format.json { render :show, status: :created, location: @log }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @log.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /logs/1 or /logs/1.json
  def update
    respond_to do |format|
      if @log.update(log_params)
        format.html { redirect_to log_url(@log), notice: "Log was successfully updated." }
        format.json { render :show, status: :ok, location: @log }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1 or /logs/1.json
  def destroy
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url, notice: "Log was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = Log.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def log_params
      params.require(:log).permit(:DateRecieved, :DateFinished, :Comment, :TaskID)
    end

    def project_exists
      begin
        taskID = log_params[:TaskID]
        taskOnIDIsNull = Project.find(taskID).nil?
        puts "]=====================================> " + taskID.to_s
        puts "]=====================================> " + taskOnIDIsNull.to_s
        return true
      rescue
        return false
      end
    end    
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_form.html.erb
<%= form_with(model: log) do |form| %>
  <% if log.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(log.errors.count, "error") %> prohibited this log from being saved:</h2>

      <ul>
        <% log.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :DateRecieved, style: "display: block" %>
    <%= form.date_field :DateRecieved, class:"form-control" %>
  </div>

  <div>
    <%= form.label :DateFinished, style: "display: block" %>
    <%= form.date_field :DateFinished, class:"form-control" %>
  </div>

  <div>
    <%= form.label :Comment, style: "display: block" %>
    <%= form.text_field :Comment, class:"form-control" %>
  </div>

  <div>
    <%= form.label :TaskID, style: "display: block" %>
    <%= form.select(:TaskID, options_for_select([[@task_priority[1],1],[@task_priority[2],2],[@task_priority[3],3]])) %>
    <!--<%= form.select(:TaskID, options_for_select(Task.all.map(&:id))) %>-->
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/logs/_log.html.erb
<div id="<%= dom_id log %>">
  <p>
    <strong>Daterecieved:</strong>
    <%= log.DateRecieved %>
  </p>

  <p>
    <strong>Datefinished:</strong>
    <%= log.DateFinished %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= log.Comment %>
  </p>

  <p>
    <strong>Taskid:</strong>
    <%= log.TaskID %>

    <% Task.all.each do |t|%>
    <% if log.TaskID==t.id%>
    — <strong> <%= link_to t.Topic,"/tasks/"+t.id.to_s %></strong>
    <%end%>
    <%end%>
  </p>
  </p>

</div>

app/views/logs/edit.html.erb
<h1>Editing log</h1>

<%= render "form", log: @log %>

<br>

<div>
  <%= link_to "Show this log", @log, class:"btn btn-info" %>
  <%= link_to "Back to logs", logs_path, class:"btn btn-secondary" %>
</div>

app/views/logs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Logs</h1>

<div id="logs">
  <% @logs.each do |log| %>
    <%= render log %>
    <p>
      <%= link_to "Show this log", log, class:"btn btn-secondary" %>
    </p>
  <% end %>
</div>

<%= link_to "New log", new_log_path, class:"btn btn-success" %>

app/views/logs/new.html.erb
<h1>New log</h1>

<%= render "form", log: @log %>

<br>

<div>
  <%= link_to "Back to logs", logs_path %>
</div>

app/views/logs/show.html.erb
<p style="color: green"><%= notice %></p>
<!--<%= render @log %>-->
<div class="jumbotron">
  <h1 class="display-4">[ID-<%=@log.id%>] <%=@log.Comment%></h1>
  <p class="lead"><%=@log.DateRecieved%> - <%=@log.DateFinished%></p>
  <hr class="my-4">
  <p>TaskID-<%=@log.TaskID%></p>
  <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
</div>
<div style="display:flex;flex-direction: row;">
  <%= link_to "Edit this log", edit_log_path(@log), class:"btn btn-warning" %>
  <%= button_to "Destroy this log", @log, method: :delete, class:"btn btn-danger" %>
</div>
<br/>
<%= link_to "Back to logs", logs_path, class:"btn btn-info" %>